---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: "./data_bags"
  roles_path: "./roles"
  environments_path: "./environments"
  client_rb:
    audit_mode: :disabled

platforms:
  - name: ubuntu-16.04
    driver_config:
      require_chef_omnibus: 12.14.89
    customize:
      memory: 1024
      cpus: 1
    require_chef_omnibus: false
  - name: ubuntu-14.04
    driver_config:
      require_chef_omnibus: 12.14.89
    customize:
      memory: 1024 #default is 256
      cpus: 1
    require_chef_omnibus: false
  - name: centos-6.8
    driver_config:
      box: bento-centos-6.8
      box_url: https://atlas.hashicorp.com/bento/boxes/centos-6.8/versions/2.3.1/providers/virtualbox.box
      require_chef_omnibus: 12.14.89
  - name: centos-7.3
    driver_config:
      box: bento-centos-7.3
      box_url: https://atlas.hashicorp.com/bento/boxes/centos-7.3/versions/2.3.2/providers/virtualbox.box
      require_chef_omnibus: 12.14.89
    customize:
      memory: 1024
      cpus: 1
  - name: oracle-6.8
    driver_config:
      box: bento-oracle-6.8
      box_url: https://atlas.hashicorp.com/bento/boxes/oracle-6.8/versions/2.3.1/providers/virtualbox.box
      require_chef_omnibus: 12.14.89
  - name: oracle-7.3
    driver_config:
      box: bento-oracle-7.3
      box_url: https://atlas.hashicorp.com/bento/boxes/oracle-7.3/versions/2.3.1/providers/virtualbox.box
      require_chef_omnibus: 12.14.89
    customize:
      memory: 1024
      cpus: 1
  - name: redhat-68
    driver_config:
      box: rhel68
      box_url: file:///Users/kirkl/Documents/rhel-6.8.virtualbox.box
    customize:
       memory: 1024 #default is 256
       cpus: 1
    require_chef_omnibus: false
  - name: redhat-73
    driver_config:
      box: rhel73
      box_url: file:///Users/kirkl/Documents/rhel-7.3.virtualbox.box
    customize:
       memory: 1024 #default is 256
       cpus: 1
    require_chef_omnibus: false

suites:
   - name: CRFsuite
     run_list:
       - recipe[CRFsuite]
